/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DomainModel.KhachHang;
import ViewModel.KhachHangView;
import Sevice.KhachHangSevice;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fptshop
 */
public class KhachHangQlJF extends javax.swing.JFrame {

    /**
     * Creates new form KhachHangQlJF
     */
    DefaultTableModel mode = new DefaultTableModel();
    private KhachHangSevice listKh = new KhachHangSevice();
    SimpleDateFormat fomat = new SimpleDateFormat("hh:mm:ss");

    void inti() {
        setLocationRelativeTo(null);
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                LbDongHo.setText(fomat.format(new Date()));
            }
        }).start();

    }

    public KhachHangQlJF() {
        initComponents();
        inti();
        mode = (DefaultTableModel) TbKhachHang.getModel();
        mode.setRowCount(0);
        loat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        jButton9 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton11 = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jButton10 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        LbDongHo = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        txtSdt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        txtThanhPho = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbKhachHang = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        txtHoVaTen = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        txtDiaChi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar2.setRollover(true);

        jButton9.setText("ĐIỆN THOẠI");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton9);

        jButton3.setText("CHI TIẾT ĐIỆN THOẠI");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton3);
        jToolBar2.add(jSeparator5);

        jButton11.setText("HÓA ĐƠN");
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton11);
        jToolBar2.add(jSeparator12);

        jButton10.setText("BẢO HÀNH");
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton10);
        jToolBar2.add(jSeparator1);

        jButton2.setText("NHÂN VIÊN");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton2);

        jButton1.setText("KHÁCH HÀNG");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        jButton12.setText("TÀI KHOẢN ");
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton12);

        jButton4.setText("CỬA HÀNG");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton4);

        jButton13.setText("ĐỔI MẬT KHẨU");
        jButton13.setFocusable(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton13);

        jButton14.setText("ĐĂNG XUẤT");
        jButton14.setFocusable(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton14);

        LbDongHo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LbDongHo.setText("12:12:12");

        jButton5.setText("XÓA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setText("MÃ KHÁCH HÀNG");

        jLabel5.setText("SỐ ĐIỆN THOẠI");

        jButton6.setText("TÌM KIẾM");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel6.setText("NGÀY SINH");

        TbKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ KH", "HỌ VÀ TÊN", "ĐỊA CHỈ", "SĐT", "NGÀY SINH", "THÀNH PHỐ"
            }
        ));
        TbKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbKhachHang);

        jLabel8.setText("THÀNH PHỐ");

        jButton7.setText("THÊM");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("SỬA");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel4.setText("HỌ VÀ TÊN");

        jLabel9.setText("ĐỊA CHỈ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(369, 369, 369)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 344, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LbDongHo)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(141, 141, 141)
                                    .addComponent(jButton7))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(104, 104, 104)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMa)
                                        .addComponent(txtHoVaTen)
                                        .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtThanhPho, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                        .addComponent(txtSdt, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                        .addComponent(txtNgaySinh))
                                    .addGap(105, 105, 105))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton8)
                                    .addGap(107, 107, 107)
                                    .addComponent(jButton5)
                                    .addGap(108, 108, 108)
                                    .addComponent(jButton6)
                                    .addGap(185, 185, 185))))
                        .addComponent(jScrollPane1))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(LbDongHo)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(379, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(163, 163, 163)
                            .addComponent(txtThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7)
                        .addComponent(jButton8)
                        .addComponent(jButton5)
                        .addComponent(jButton6))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(41, 41, 41)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void loat() {
        List<KhachHangView> kh = listKh.select();
        for (KhachHangView khachHangView : kh) {
            mode.addRow(new Object[]{
                khachHangView.getMaKH(),
                khachHangView.getHoVaTen(),
                khachHangView.getDiaChi(),
                khachHangView.getSdt(),
                khachHangView.getNgaySinh(),
                khachHangView.getThanhPho()
            });
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int row = TbKhachHang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "chưa chọn thông tin vui lòng click vào thông tin muốn sửa");
            return;
        } else {
            String ma = txtMa.getText();
            try {
                listKh.delete(ma);
                mode.setRowCount(0);
                loat();
                reset();
                return;
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String ma = JOptionPane.showInputDialog(null, "vui lòng nhập mã muốn tìm");
        try {
            List<KhachHang> kh = listKh.select1(ma);
            mode.setRowCount(0);
            for (KhachHang khachHang : kh) {
                mode.addRow(new Object[]{
                    khachHang.getMaKH(),
                    khachHang.getHoVaTen(),
                    khachHang.getDiaChi(),
                    khachHang.getSdt(),
                    khachHang.getNgaySinh(),
                    khachHang.getThanhPho()
                });
            }
            reset();
            return;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void TbKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbKhachHangMouseClicked
        // TODO add your handling code here:
        int row = TbKhachHang.getSelectedRow();
        KhachHang list = listKh.fina().get(row);
        txtMa.setText(list.getMaKH());
        txtHoVaTen.setText(list.getHoVaTen());
        txtDiaChi.setText(list.getDiaChi());
        txtSdt.setText(list.getSdt());
        txtNgaySinh.setText(list.getNgaySinh());
        txtThanhPho.setText(list.getThanhPho());
    }//GEN-LAST:event_TbKhachHangMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String ma = txtMa.getText();
        String hoVaTen = txtHoVaTen.getText();
        String DiaChi = txtDiaChi.getText();
        String Sdt = txtSdt.getText();
        String NgaySinh = txtNgaySinh.getText();
        String ThanhPho = txtThanhPho.getText();
        if (ma.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "vui lòng nhập mã khách hàng");
            return;
        }
        if (ma.trim().toUpperCase().startsWith("KH") == false && ma.trim().toUpperCase().startsWith("kh") == false) {
            JOptionPane.showMessageDialog(null, "mã khách hàng phải nhập KH ở đầu ");
            return;
        }

        if (hoVaTen.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "vui lòng nhập tên khách hàng");
            return;
        }
        int check = 0;
        for (int i = 0; i < hoVaTen.trim().length(); i++) {
            if (hoVaTen.trim().charAt(i) >= '0' && hoVaTen.trim().charAt(i) <= '9') {
                check = 1;
                JOptionPane.showMessageDialog(null, "tên khách hàng ko được nhập số");
                return;
            }
        }
        if (DiaChi.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "vui lòng nhập địa chỉ khách hàng");
            return;
        }
        for (int i = 0; i < DiaChi.trim().length(); i++) {
            if (DiaChi.trim().charAt(i) >= '0' && DiaChi.trim().charAt(i) <= '9') {
                check = 1;
                JOptionPane.showMessageDialog(null, "địa chỉ khách hàng ko được nhập số");
                return;
            }
        }
        if (Sdt.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "vui lòng nhập số điện thoại khách hàng");
            return;
        }
        if (Sdt.trim().length() < 10 && Sdt.trim().length() > 10) {
            JOptionPane.showMessageDialog(null, "số điện thoại khách hàng phải 10 số");
            return;
        }
        try {
            int sdt = Integer.parseInt(Sdt);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "vui lòng nhập số điện thoại khách hàng là số ");
            return;
        }

        if (NgaySinh.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "vui lòng nhập ngày sinh khách hàng");
            return;
        }
        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
        Date ht = new Date();
        try {
            Date d = fm.parse(NgaySinh);
            if (d.after(ht)) {
                JOptionPane.showMessageDialog(null, "ko được nhập quá ngày hiện tại");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "vui lòng nhập ngày đúng định dạng yyyy-MM-dd");
            return;
        }
        if (ThanhPho.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "vui lòng nhập thành phố đang sống của  khách hàng");
            return;
        }
        for (int i = 0; i < ThanhPho.trim().length(); i++) {
            if (ThanhPho.trim().charAt(i) >= '0' && ThanhPho.trim().charAt(i) <= '9') {
                check = 1;
                JOptionPane.showMessageDialog(null, "thành phố khách hàng ko được nhập số");
                return;
            }
        }

        try {
            listKh.insert(ma, hoVaTen, DiaChi, Sdt, NgaySinh, ThanhPho);
            mode.setRowCount(0);
            loat();
            reset();
            return;
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int row = TbKhachHang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "chưa chọn thông tin vui lòng click vào thông tin muốn sửa");
            return;
        } else {
            String ma = txtMa.getText();
            String hoVaTen = txtHoVaTen.getText();
            String DiaChi = txtDiaChi.getText();
            String Sdt = txtSdt.getText();
            String NgaySinh = txtNgaySinh.getText();
            String ThanhPho = txtThanhPho.getText();
            if (ma.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "vui lòng nhập mã khách hàng");
                return;
            }
            if (ma.trim().toUpperCase().startsWith("KH") == false && ma.trim().toUpperCase().startsWith("kh") == false) {
                JOptionPane.showMessageDialog(null, "mã khách hàng phải nhập KH ở đầu ");
                return;
            }

            if (hoVaTen.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "vui lòng nhập tên khách hàng");
                return;
            }
            int check = 0;
            for (int i = 0; i < hoVaTen.trim().length(); i++) {
                if (hoVaTen.trim().charAt(i) >= '0' && hoVaTen.trim().charAt(i) <= '9') {
                    check = 1;
                    JOptionPane.showMessageDialog(null, "tên khách hàng ko được nhập số");
                    return;
                }
            }
            if (DiaChi.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "vui lòng nhập địa chỉ khách hàng");
                return;
            }
            for (int i = 0; i < DiaChi.trim().length(); i++) {
                if (DiaChi.trim().charAt(i) >= '0' && DiaChi.trim().charAt(i) <= '9') {
                    check = 1;
                    JOptionPane.showMessageDialog(null, "địa chỉ khách hàng ko được nhập số");
                    return;
                }
            }
            if (Sdt.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "vui lòng nhập số điện thoại khách hàng");
                return;
            }
            if (Sdt.trim().length() < 10 && Sdt.trim().length() > 10) {
                JOptionPane.showMessageDialog(null, "số điện thoại khách hàng phải 10 số");
                return;
            }
            try {
                int sdt = Integer.parseInt(Sdt);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "vui lòng nhập số điện thoại khách hàng là số ");
                return;
            }

            if (NgaySinh.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "vui lòng nhập ngày sinh khách hàng");
                return;
            }
            SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
            Date ht = new Date();
            try {
                Date d = fm.parse(NgaySinh);
                if (d.after(ht)) {
                    JOptionPane.showMessageDialog(null, "ko được nhập quá ngày hiện tại");
                    return;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "vui lòng nhập ngày đúng định dạng yyyy-MM-dd");
                return;
            }
            if (ThanhPho.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "vui lòng nhập thành phố đang sống của  khách hàng");
                return;
            }
            for (int i = 0; i < ThanhPho.trim().length(); i++) {
                if (ThanhPho.trim().charAt(i) >= '0' && ThanhPho.trim().charAt(i) <= '9') {
                    check = 1;
                    JOptionPane.showMessageDialog(null, "thành phố khách hàng ko được nhập số");
                    return;
                }
            }

            try {
                listKh.update(ma, hoVaTen, DiaChi, Sdt, NgaySinh, ThanhPho);
                mode.setRowCount(0);
                loat();
                reset();
                return;
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed
    void reset() {
        txtMa.setText("");
        txtHoVaTen.setText("");
        txtDiaChi.setText("");
        txtSdt.setText("");
        txtNgaySinh.setText("");
        txtThanhPho.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHangQlJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHangQlJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHangQlJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHangQlJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHangQlJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbDongHo;
    private javax.swing.JTable TbKhachHang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtThanhPho;
    // End of variables declaration//GEN-END:variables
}
